### ISSUE TITLE
TZConvert.GetTimeZoneInfo() regression between v5.0.0 and v6.0.1

### ISSUE THREAD

**Issue by robsonj** [mattjohnsonpint/TimeZoneConverter#133]
Hi There,

The follow unit test passes using v5.0.0 of TimeZoneConverter, but fails (on the last line) of the unit test when using v6.0.1. There seems to have been a regression in `TZConvert.GetTimeZoneInfo()` between the two releases, we have rolled back to v5.0.0 for now, awaiting further guidance please.

```
        [Test]
        public void TZConvertBreaksTimeZoneConversion()
        {
            var today = DateTime.Today;

            TimeZoneInfo localTimeZone = TimeZoneInfo.Local;
            TZConvert.GetTimeZoneInfo(localTimeZone.Id);

            Assert.DoesNotThrow(() => TimeZoneInfo.ConvertTime(today, TimeZoneInfo.Local, localTimeZone));
            Assert.DoesNotThrow(() => TimeZoneInfo.ConvertTime(today, localTimeZone,      localTimeZone));
        }
```

Thrown exception (when using v6.0.1)...

```
  Expected: No Exception to be thrown
  But was:  <System.ArgumentException: The conversion could not be completed because the supplied DateTime did not have the Kind property set correctly.  For example, when the Kind property is DateTimeKind.Local, the source time zone must be TimeZoneInfo.Local. (Parameter 'sourceTimeZone')
   at System.TimeZoneInfo.ConvertTime(DateTime dateTime, TimeZoneInfo sourceTimeZone, TimeZoneInfo destinationTimeZone, TimeZoneInfoOptions flags, CachedData cachedData)
   at System.TimeZoneInfo.ConvertTime(DateTime dateTime, TimeZoneInfo sourceTimeZone, TimeZoneInfo destinationTimeZone)
 ...
   ```

Cheers
Jonathan

**Comment by mattjohnsonpint** [comment]
Thanks for reporting!  I'll investigate asap.

**Comment by mattjohnsonpint** [comment]
Hi, sorry for the delay.  I ran the test you provided, and it passes for me.  That said, I'm not sure exactly what it supposed to be testing, as the result is discarded, and the conversion is always between the same actual object instances.

I *can* get it to fail if I change the third line of the test to `localTimeZone = TZConvert.GetTimeZoneInfo(localTimeZone.Id);`  That would be expected though, and is not related to TimeZoneConverter, or anything new.

Fundamentally, `TimeZoneInfo.Local` is not the same as `TimeZoneInfo.FindSystemTimeZoneById(TimeZoneInfo.Local.Id)` (or the equivalent `TZConvert.GetTimeZoneInfo(TimeZoneInfo.Local.Id)`) because the former is affected by the `Automatically adjust clock for Daylight Saving Time` setting on Windows machines, where the latter is not.  More on this at https://learn.microsoft.com/dotnet/api/system.timezoneinfo.local#remarks

Just to validate nothing changed with TimeZoneConverter, here's a simple program:

```csharp
using TimeZoneConverter;

TimeZoneInfo tz = TZConvert.GetTimeZoneInfo(TimeZoneInfo.Local.Id);
DateTime result = TimeZoneInfo.ConvertTime(DateTime.Now, tz, TimeZoneInfo.Utc);
Console.WriteLine(result);
```

It too will fail with the exception you mentioned, regardless of whether using TimeZoneConverter 6.0.1 or 5.0.0.
