### ISSUE TITLE
Missing America/Ciudad_Juarez

### ISSUE THREAD

**Issue by tomaszadamski-mp** [mattjohnsonpint/TimeZoneConverter#136]

**Comment by yzhoholiev** [comment]
Also got this issue today in combination with the latest versions (5.2.0) of the GeoTimeZone library.

**Comment by mattjohnsonpint** [comment]
I'm not sure that Microsoft has made a corresponding Windows time zone yet.  I'll see what I can find out.  Thanks.

**Comment by mattjohnsonpint** [comment]
Related https://unicode-org.atlassian.net/browse/CLDR-16181

**Comment by mattjohnsonpint** [comment]
Until Microsoft and CLDR are updated, I'm going to make the following mappings in TimeZoneConverter, because they are the most rational for present-day forward:

- `America/Ciudad_Juarez` => `Mountain Standard Time` (to match US DST rules)
- `America/Ojinaga` => `Central Standard Time` (to match US DST rules)
- `America/Chihuahua` => `Central Standard Time (Mexico)` (to match Mexico City)

**Comment by mattjohnsonpint** [comment]
Raised a new issue for CLDR to match:
https://unicode-org.atlassian.net/browse/CLDR-16386

**Comment by mattjohnsonpint** [comment]
This is fixed in the latest 6.1.0 release.  Thanks!
