### ISSUE TITLE
The `TZConvert.TryGetTimeZoneInfo` changes the instance of TimeZoneInfo.Local

### ISSUE THREAD

**Issue by KaNaDaAT** [mattjohnsonpint/TimeZoneConverter#143]
When using the following code in 5.0.0 the test works just fine.
```csharp
[TestMethod]
public void TryGetTimeZoneInfoBehavior()
{
	var localTimeInstanceBefore = TimeZoneInfo.Local;
	TimeZoneConverter.TZConvert.TryGetTimeZoneInfo("Central European Standard Time", out var _);
	var localTimeInstanceAfter = TimeZoneInfo.Local;
	Assert.AreSame(localTimeInstanceBefore, localTimeInstanceAfter);
}
```
I am currently using version 6.0.0 and the test fails. It seems like the TZConvert.TryGetTimeZoneInfo changes the instance of TimeZoneInfo.Local what in my opinion should not happen.

**Comment by KaNaDaAT** [comment]
My guess is the CachedData is cleared directly or by a System method that is used.

**Comment by mattjohnsonpint** [comment]
Hi.  Sorry for the delay in response.

Yes, on first usage of TimeZoneConverter, the static constructor on `TZConvert` loads all of the data, including the time zones from the local system via the internal `GetSystemTimeZones` method.  When doing so, it first clears the local cache.

https://github.com/mattjohnsonpint/TimeZoneConverter/blob/dbc4c8029cb51842b8b40d3913e373f0eaee2ac1/src/TimeZoneConverter/TZConvert.cs#L544-L548

This is to prevent conversion errors caused by any previous calls to `TimeZoneInfo.FindSystemTimeZoneById` that may have used non-standard casing (i.e., "eAsTeRn StaNdArd TiME", or just all lower or upper cased, etc.).  We don't want those in the results returned by our call to `TimeZoneInfo.GetSystemTimeZones`.

A side effect of clearing the cache is that the cached copy of `TimeZoneInfo.Local` is also discarded, and recomputed on next call to `TimeZoneInfo.Local`.  There's not much we can do about this.

Generally speaking though, it should not matter that two `TimeZoneInfo` instances derived from `TimeZoneInfo.Local` are not the same instance - unless you're specifically trying to _ignore_ local time zone changes between calls.

To be clear, the cache is not cleared on each call to `TZConvert.TryGetTimeZoneInfo`.  It's only occurring the _first_ time you use the `TZConvert` class.  So any performance impact should be negligable.

If you really need the same instance, you can make some call to the `TZConvert` class before getting the local time zone.  For example, add this as the first line to your test, and it will pass:

```csharp
_ = TZConvert.KnownIanaTimeZoneNames;
```

Thanks.
