### ISSUE TITLE
Version control feature request: include raw csv files instead of tar.gz binary files in version control so any diffs can be seen easily

### ISSUE THREAD

**Issue by theyetiman** [mattjohnsonpint/TimeZoneConverter#93]
by all means include the tar.gz files in version control, too, if it's easier. Alternatively zip the files on build outside of version control.

**Comment by mattjohnsonpint** [comment]
Rather than go that route, I've started using [Verify](https://github.com/VerifyTests/Verify) in the unit tests.  You'll see test output [in the test directory](https://github.com/mattjohnsonpint/TimeZoneConverter/tree/main/test/TimeZoneConverter.Tests) for all of the verification tests that are run each build.

This gets you a slightly better effect than diffing the data files, as you can see the actual changes in output - regardless of how I choose to persist it internally.

Thanks.
