### ISSUE TITLE
Is there a way to determine most used timezones among an offset?

### ISSUE THREAD

**Issue by zoinkydoink** [mattjohnsonpint/TimeZoneConverter#98]
Let say among all Eastern Standard Time, there is a bunch of them but is there a way to determine that most popular one of these? reason why i ask is, i have a minute offset that i match to a timezone, but right now it always picks `Havana `for EST because that is the "first" in the list, I think the right one would be `Eastern Time (Canada & US)`
Probably a long shot but I thought I would ask.

**Comment by mattjohnsonpint** [comment]
"popular" is very subjective.  You'd also have to cross-reference something like population statistics.

Also, just because you have an offset doesn't mean you can map it to a time zone.  Just thinking about the continental US, -5 might be EST, but it also might be CDT.  Even if you have the date and time, there is some ambiguity due to overlap during the transition where both are in effect simultaneously.

Anyway, this is a better question for Stack Overflow than for this library.  But I would probably answer it the same way.
